name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login to Azure using Managed Identity
        uses: azure/login@v1
        with:
          identity: ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENT_ID }}  # Client ID of the User Assigned Managed Identity (costerraformumi)
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Your Tenant ID
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Your Azure Subscription ID

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
